cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization,Content-Type,Accept}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}
  max-age: ${CORS_MAX_AGE:3600}

# Enables multi-issuer feature.
# Can be used also as a single issuer server solution by keeping only one known issuer
oauth:
  jwt:
    known-issuers:
      - "https://login.microsoftonline.com/${AZURE_AD_TENANT_ID:cc25bc2e-b3cb-4d85-ad7c-33745bf2a224}/v2.0"
      #      - "https://cognito-idp.${COGNITO_REGION:us-east-1}.amazonaws.com/${COGNITO_USER_POOL_ID:us-east-1_abcdefg}"
      - "https://accounts.google.com"
