spring:
  application:
    name: spring-kotlin-accelerator
  profiles:
    active: ${ACTIVE_PROFILE:local}
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${POSTGRES_DB:spring_kotlin}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
  reactor:
    context-propagation: auto
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      lifecycle-management: start_and_stop

logging:
  pattern:
    console: "%boldGreen(%d{yy-MM-dd}) %boldGreen(%d{HH:mm:ss.SSS}) | %boldMagenta(%-15.15mdc{traceId} %-15.15mdc{spanId} %-15.15mdc{thread}) | %highlight(%-5.5level) | %-15.15logger{15} | %boldCyan(%-10.10mdc{folder}) | %m%n"

server:
  port: ${SERVER_PORT:8080}
